In [11]:
import pandas as pd

In [12]:
df = pd.read_csv(r"C:\Users\vchan\OneDrive\Desktop\mumbai_local\data\processed\stations_clean.csv")
print(df.shape)
df.head()

(139, 9)

,station,station_code,line,platforms,tracks,year_of_opening,nearby_attractions,distance_km,travel_time_min
0,Churchgate,CCG,Western,4.0,4.0,1867.0,"Marine Drive,Nariman Point,Flora Fountain",0,0
1,Marine Lines,MEL,Western,4.0,4.0,1867.0,"Marine Drive,Girgaum Chowpatty Beach,Taraporew...",1,3
2,Charni Road,CYR,Western,4.0,4.0,1867.0,"Girgaum Chowpatty Beach,Taraporewala Aquarium,...",1,2
3,Grant Road,GTR,Western,4.0,4.0,NaN,"Taraporewala Aquarium,Girgaum Chowpatty Beach,...",1,3
4,Mumbai Central,MMCT,Western,9.0,9.0,1930.0,"Haji Ali Dargah,Mahalakshmi Temple,Nehru Plane...",1,2

## Target 1: Western Line

In [13]:
western = df[df['line'] == 'Western'].copy()
western.shape

(37, 9)

In [14]:
western[['station', 'travel_time_min']]

           station  travel_time_min
0       Churchgate                0
1     Marine Lines                3
2      Charni Road                2
3       Grant Road                3
4   Mumbai Central                2
5      Mahalakshmi                3
6      Lower Parel                3
7       Prabhadevi                3
8            Dadar                2
9     Matunga Road                2
10        Mahim Jn                3
11          Bandra                4
12       Khar Road                3
13       Santacruz                2
14      Vile Parle                3
15         Andheri                5
16      Jogeshwari                3
17      Ram Mandir                3
18        Goregaon                2
19           Malad                4
20       Kandivali                3
21        Borivali                6
22         Dahisar                5
23       Mira Road                5
24       Bhayander                5
25         Naigaon                6
26      Vasai Road                5
27    Nalla Sopara                5
28           Virar                6
29        Vaitarna                9
30         Saphale                8
31      Kelve Road                8
32         Palghar               15
33     Umroli Road                6
34          Boisar                6
35         Vangaon                9
36     Dahanu Road               13

## Western Full timetable

In [15]:
from datetime import datetime, timedelta

trains = []
start_time = datetime.strptime("04:00", "%H:%M")
end_time = datetime.strptime("23:00", "%H:%M")
frequency = 10  # every 10 minutes

train_no = 1
current_start = start_time

while current_start <= end_time:
    current_time = current_start
    for i, row in western.iterrows():
        current_time += timedelta(minutes=row['travel_time_min'])
        trains.append({
            'train_id': f'WR_{str(train_no).zfill(3)}',
            'station': row['station'],
            'station_code': row['station_code'],
            'line': 'Western',
            'arrival_time': current_time.strftime("%H:%M"),
            'stop_number': list(western.index).index(i) + 1
        })
    train_no += 1
    current_start += timedelta(minutes=frequency)

timetable_wr = pd.DataFrame(trains)
print(timetable_wr.shape)

(4255, 6)

In [16]:
timetable_wr

     train_id         station station_code     line arrival_time  stop_number
0      WR_001      Churchgate          CCG  Western        04:00            1
1      WR_001    Marine Lines          MEL  Western        04:03            2
2      WR_001     Charni Road          CYR  Western        04:05            3
3      WR_001      Grant Road          GTR  Western        04:08            4
4      WR_001  Mumbai Central         MMCT  Western        04:10            5
...       ...             ...          ...      ...          ...          ...
4250   WR_115         Palghar          PLG  Western        01:21           33
4251   WR_115     Umroli Road          UOI  Western        01:27           34
4252   WR_115          Boisar          BOR  Western        01:33           35
4253   WR_115         Vangaon          VGN  Western        01:42           36
4254   WR_115     Dahanu Road          DRD  Western        01:55           37

[4255 rows x 6 columns]

## Central Line

In [19]:
central = df[df['line'] == 'Central 1'].copy()
central.shape

(40, 9)

In [20]:
central[['station', 'travel_time_min']]

           station  travel_time_min
37            CSMT                0
38          Masjid                3
39  Sandhurst Road                2
40         Byculla                3
41     Chinchpokli                2
42     Currey Road                2
43           Parel                3
44           Dadar                3
45         Matunga                3
46            Sion                4
47           Kurla                4
48     Vidhyavihar                3
49       Ghatkopar                3
50        Vikhroli                5
51     Kanjur Marg                3
52         Bhandup                3
53           Nahur                3
54          Mulund                3
55           Thane                4
56           Kalva                4
57          Mumbra                6
58         Diva Jn                4
59           Kopar                5
60        Dombivli                3
61        Thakurli                3
62          Kalyan                6
63      Vithalwadi                5
64     Ulhas Nagar                3
65       Ambernath                6
66        Badalpur                8
67         Vangani                9
68           Shelu                4
69           Neral                4
70   Bhivpuri Road                7
71          Karjat                9
72      Palasdhari                5
73         Kelavli                7
74         Dolavli                3
75          Lowjee                4
76         Khopoli                6

##  Central Timtable

In [21]:
trains = []
start_time = datetime.strptime("04:00", "%H:%M")
end_time = datetime.strptime("23:00", "%H:%M")
frequency = 10  # every 10 minutes

train_no = 1
current_start = start_time

while current_start <= end_time:
    current_time = current_start
    for i, row in central.iterrows():
        current_time += timedelta(minutes=row['travel_time_min'])
        trains.append({
            'train_id': f'CR_{str(train_no).zfill(3)}',
            'station': row['station'],
            'station_code': row['station_code'],
            'line': 'Central',
            'arrival_time': current_time.strftime("%H:%M"),
            'stop_number': list(central.index).index(i) + 1
        })
    train_no += 1
    current_start += timedelta(minutes=frequency)

timetable_cr = pd.DataFrame(trains)
print(timetable_cr.shape)

(4600, 6)

In [22]:
timetable_cr

     train_id         station station_code     line arrival_time  stop_number
0      CR_001            CSMT      CSMT/ST  Central        04:00            1
1      CR_001          Masjid          MSD  Central        04:03            2
2      CR_001  Sandhurst Road         SNRD  Central        04:05            3
3      CR_001         Byculla           BY  Central        04:08            4
4      CR_001     Chinchpokli          CHG  Central        04:10            5
...       ...             ...          ...      ...          ...          ...
4595   CR_115      Palasdhari          PDI  Central        01:27           36
4596   CR_115         Kelavli          KLY  Central        01:34           37
4597   CR_115         Dolavli          DLV  Central        01:37           38
4598   CR_115          Lowjee          LWJ  Central        01:41           39
4599   CR_115         Khopoli           KP  Central        01:47           40

[4600 rows x 6 columns]

## HarbourLine

In [23]:
harbour = df[df['line'] == 'Harbour'].copy()
harbour.shape

(25, 9)

In [25]:
harbour[['station', 'travel_time_min']]

            station  travel_time_min
114            CSMT                0
115          Masjid                3
116  Sandhurst Road                2
117  Dockyarad Road                2
118       Reay Road                2
119    Cotton Green                2
120           Sewri                3
121     Vadala Road                3
122       GTB Nagar                4
123     Chunabhatti                3
124           Kurla                3
125      Tilaknagar                3
126         Chembur                2
127         Govandi                3
128        Mankhurd                3
129           Vashi                8
130         Sanpada                3
131        Juinagar                5
132           Nerul                3
133  Seawood Darave                3
134     Belapur CBD                4
135        Kharghar                4
136      Mansarovar                3
137     Khandeshwar                3
138          Panvel                3

## Harbour Timtable

In [26]:
trains = []
start_time = datetime.strptime("04:00", "%H:%M")
end_time = datetime.strptime("23:00", "%H:%M")
frequency = 10  # every 10 minutes

train_no = 1
current_start = start_time

while current_start <= end_time:
    current_time = current_start
    for i, row in harbour.iterrows():
        current_time += timedelta(minutes=row['travel_time_min'])
        trains.append({
            'train_id': f'HR_{str(train_no).zfill(3)}',
            'station': row['station'],
            'station_code': row['station_code'],
            'line': 'Harbour',
            'arrival_time': current_time.strftime("%H:%M"),
            'stop_number': list(harbour.index).index(i) + 1
        })
    train_no += 1
    current_start += timedelta(minutes=frequency)

timetable_hr = pd.DataFrame(trains)
print(timetable_hr.shape)

(2875, 6)

In [27]:
timetable_hr

     train_id         station station_code     line arrival_time  stop_number
0      HR_001            CSMT      CSMT/ST  Harbour        04:00            1
1      HR_001          Masjid          MSD  Harbour        04:03            2
2      HR_001  Sandhurst Road         SNRD  Harbour        04:05            3
3      HR_001  Dockyarad Road         DKRD  Harbour        04:07            4
4      HR_001       Reay Road          RRD  Harbour        04:09            5
...       ...             ...          ...      ...          ...          ...
2870   HR_115     Belapur CBD         BEPR  Harbour        00:04           21
2871   HR_115        Kharghar         KHAG  Harbour        00:08           22
2872   HR_115      Mansarovar         MANR  Harbour        00:11           23
2873   HR_115     Khandeshwar         KNDS  Harbour        00:14           24
2874   HR_115          Panvel         PNVL  Harbour        00:17           25

[2875 rows x 6 columns]

### Total Values

In [29]:
timetable = pd.concat([timetable_wr, timetable_cr, timetable_hr], ignore_index=True)
print(timetable.shape)
timetable['line'].value_counts()

(11730, 6)

line
Central    4600
Western    4255
Harbour    2875
Name: count, dtype: int64

### Saving the file

In [30]:
timetable.to_csv(r"C:\Users\vchan\OneDrive\Desktop\mumbai_local\data\processed\timetable.csv", index=False)
print("Saved!")

Saved!